<?php
if (!defined('ABSPATH')) exit;
add_shortcode('hirehub_jobs','hirehub_jobs_shortcode');
function hirehub_jobs_shortcode($atts){ ob_start(); ?>
<section class="hh-jobs"><form id="hh-job-search" class="hh-search"><input name="search" placeholder="Search jobs or skills"><input name="location" placeholder="Location"><select name="job_type"><option value="">All job types</option><option>Full Time</option><option>Part Time</option><option>Contract</option><option>Remote</option></select><button>Search</button></form><div id="hh-job-results"><?php echo hirehub_render_jobs(); ?></div></section><?php return ob_get_clean(); }
function hirehub_render_jobs($args=array()){
 $q=new WP_Query(wp_parse_args($args,array('post_type'=>'hirehub_job','posts_per_page'=>10,'paged'=>1)));
 if(!$q->have_posts()) return '<p class="hh-empty">No jobs found.</p>';
 $html='<div class="hh-grid">'; while($q->have_posts()){ $q->the_post(); $id=get_the_ID(); $html.='<article class="hh-card"><span class="hh-badge">'.esc_html(get_post_meta($id,'_company',true)).'</span><h3>'.esc_html(get_the_title()).'</h3><p>'.esc_html(get_post_meta($id,'_location',true)).' · '.esc_html(get_post_meta($id,'_experience',true)).'</p><p>'.esc_html(get_post_meta($id,'_salary',true)).'</p><a class="hh-button" href="'.esc_url(get_permalink()).'">View Job</a></article>'; } wp_reset_postdata(); return $html.'</div>';
}
add_shortcode('hirehub_apply','hirehub_apply_shortcode');
function hirehub_apply_shortcode($atts){ $atts=shortcode_atts(array('job_id'=>0),$atts); $job_id=absint($atts['job_id']) ?: absint($_GET['job_id'] ?? 0); if(!$job_id) return '<p>Select a job first.</p>'; if(!is_user_logged_in()) return '<p>Please <a href="'.esc_url(wp_login_url(get_permalink())).'">log in</a> to apply.</p>'; if(!current_user_can('read')) return ''; ob_start(); ?><form class="hh-form" method="post" enctype="multipart/form-data"><input type="hidden" name="hh_action" value="apply"><input type="hidden" name="job_id" value="<?php echo esc_attr($job_id); ?>"><?php wp_nonce_field('hirehub_apply','hh_nonce'); ?><label>Resume (PDF/DOC/DOCX)<input type="file" name="resume" accept=".pdf,.doc,.docx" required></label><label>Cover letter<textarea name="cover_letter" rows="6"></textarea></label><button class="hh-button">Apply Now</button></form><?php return ob_get_clean(); }
add_action('init',function(){ if(empty($_POST['hh_action']) || $_POST['hh_action']!=='apply') return; if(!is_user_logged_in() || !wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['hh_nonce'] ?? '')),'hirehub_apply')) wp_die('Security check failed.'); $job_id=absint($_POST['job_id']); if(get_post_type($job_id)!=='hirehub_job') wp_die('Invalid job.'); if(empty($_FILES['resume']['name'])) wp_die('Resume is required.'); require_once ABSPATH.'wp-admin/includes/file.php'; $file=wp_handle_upload($_FILES['resume'],array('test_form'=>false,'mimes'=>array('pdf'=>'application/pdf','doc'=>'application/msword','docx'=>'application/vnd.openxmlformats-officedocument.wordprocessingml.document'))); if(isset($file['error'])) wp_die(esc_html($file['error'])); $result=hirehub_submit_application($job_id,get_current_user_id(),$file['url'],sanitize_textarea_field(wp_unslash($_POST['cover_letter'] ?? ''))); wp_die(is_wp_error($result)?esc_html($result->get_error_message()):'Application submitted successfully.'); });
add_shortcode('hirehub_dashboard','hirehub_dashboard_shortcode');
function hirehub_dashboard_shortcode(){ if(!is_user_logged_in()) return '<p>Please log in.</p>'; $apps=hirehub_get_candidate_applications(get_current_user_id()); ob_start(); echo '<div class="hh-dashboard"><h2>My Applications</h2>'; if(!$apps) echo '<p>No applications yet.</p>'; else { echo '<div class="hh-table"><div class="hh-row hh-head"><b>Job</b><b>Status</b><b>Applied</b></div>'; foreach($apps as $a){ echo '<div class="hh-row"><span>'.esc_html(get_the_title($a->job_id)).'</span><span>'.esc_html(ucfirst($a->status)).'</span><span>'.esc_html(mysql2date(get_option('date_format'),$a->created_at)).'</span></div>'; } echo '</div>'; } echo '</div>'; return ob_get_clean(); }
add_shortcode('hirehub_post_job','hirehub_post_job_shortcode');
function hirehub_post_job_shortcode(){ if(!is_user_logged_in() || !current_user_can('edit_posts')) return '<p>Recruiter access required.</p>'; ob_start(); ?><form class="hh-form" method="post"><input type="hidden" name="hh_action" value="post_job"><?php wp_nonce_field('hirehub_post_job','hh_post_nonce'); ?><label>Job title<input name="title" required></label><label>Description<textarea name="description" rows="8" required></textarea></label><label>Company<input name="company" required></label><label>Location<input name="location" required></label><label>Salary<input name="salary"></label><label>Experience<input name="experience"></label><label>Skills<input name="skills" placeholder="WordPress, PHP, MySQL"></label><button class="hh-button">Publish Job</button></form><?php return ob_get_clean(); }
add_action('init',function(){ if(($_POST['hh_action']??'')!=='post_job' || !is_user_logged_in() || !current_user_can('edit_posts')) return; if(!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['hh_post_nonce']??'')),'hirehub_post_job')) return; $id=wp_insert_post(array('post_type'=>'hirehub_job','post_status'=>'publish','post_title'=>sanitize_text_field(wp_unslash($_POST['title'])),'post_content'=>wp_kses_post(wp_unslash($_POST['description'])),'post_author'=>get_current_user_id())); if($id && !is_wp_error($id)){ foreach(array('company','location','salary','experience','skills') as $k) update_post_meta($id,'_'.$k,sanitize_text_field(wp_unslash($_POST[$k]??''))); wp_safe_redirect(get_permalink($id)); exit; } });
